### ISSUE TITLE
‘本文链接’和‘版权声明’取消不掉

### ISSUE THREAD

**Issue by HaiyangYu1999** [cofess/hexo-theme-pure#128]
即使设置了copyright = false, 仍然在页面最下边显示
> 本文链接： https://....
    版权声明： 本博客所有文章除特别声明外，均采用 CC BY 4.0 CN协议 许可协议。转载请注明出处！
```
# Site
site:
  logo:
    enabled: true
    width: 40
    height: 40
    url: ../images/logo.png
  title: Hexo # 页面title
  favicon: /favicon.png
  board: <p>个人博客正式上线, 不断优化中!</p> # 站点公告
  copyright: false # 底部版权信息
```
