### ISSUE TITLE
Highlight inline code block

### ISSUE THREAD

**Issue by TerminalWitchcraft** [cofess/hexo-theme-pure#57]
It will be good if we can highlight the inline code block as currently, we cannot visually distinguish between inline code block and normal text.

**Comment by cofess** [comment]
like this <code>some code</code> ?

**Comment by TerminalWitchcraft** [comment]
Yes exactly.

**Comment by inkss** [comment]
@TerminalWitchcraft 修改 css 里的样式。
```css
code {
  padding: 0.2em 0.3em;
  margin: 0;
  font-size: 85%;
  background-color: rgb(27,31,35,0.05);
  border-radius: 3px;
}
```
效果是这样的：https://inkss.cn/2018/09/10/linux-system-commands/
