### ISSUE TITLE
代码块高亮如何跟你的一样，macOS窗口风格。

### ISSUE THREAD

**Issue by 2tree** [cofess/hexo-theme-pure#72]

**Comment by 2tree** [comment]
<img width="516" alt="wx20181218-140457 2x" src="https://user-images.githubusercontent.com/37758312/50135157-20e66780-02ce-11e9-9a44-902f81f5d03f.png">

**Comment by kajweb** [comment]
默认就是吧

**Comment by kajweb** [comment]
使用的是下面的CSS。
```css
.highlight:before {
    display: block;
    content: ' ';
    height: 32px;
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    background-color: #f6f6f6;
    padding: 0 10px;
    border-top-left-radius: 4px;
    border-top-right-radius: 4px;
}
```
